version: "2.1"

services:
  ruby:
    build: ruby
    env_file: docker-env
    #command: bin/rails server --port 3000 --binding 0.0.0.0    # For server container only
    ports:
      - "3000:3000"   # To change for port 80 ?
    volumes:
      - ~/Documents/www/ruby/ror:/var/www/html
    tty: true

  db:
    image: percona:latest
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "./docker/db/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "mysql:/var/lib/mysql"
    tty: true

volumes:
  mysql: {}
