version: "3.3"

services:
  ruby:
    build:
      context: ruby
      cache_from:
        - ruby:latest
      args:
        - app_home=/var/www/html/
    env_file: docker-env
    #command: bin/rails server --port 3000 --binding 0.0.0.0    # For server container only
    ports:
      - "3000:3000"   # To change for port 80 ?
    volumes:
      - "~/Documents/www/ruby/ror:/var/www/html:delegated"  #Second path must be the same as app_home args
    tty: true

  db:
    build: db
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    tty: true

volumes:
  mysql: {}
