FROM percona:latest

MAINTAINER Axel PERROUD <axel.perroud@outlook.com>
LABEL maintainer="Axel PERROUD <axel.perroud@outlook.com>"

# Install custom DB configuration
COPY custom.cnf /etc/mysql/conf.d/